# -*- coding: utf-8 -*-
"""AQI_Data_Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gH6BBcRHRIHZV4k9hj7J6JISoiIbNCPi
"""

# ✅ Install dependencies (only once)
!pip install pandas requests

# ✅ Step 1: Set your API keys manually
OPENWEATHER_API_KEY = "ee88310481e99a7843bdedc0cca27fd1"
AQICN_API_TOKEN = "2eb7e59a27fec6826892da8d9b3f9ff95e6c573e"

# ✅ Step 2: Import libraries
import requests
import pandas as pd
from datetime import datetime
import os

# ✅ Step 3: Karachi coordinates
LAT, LON = 24.8607, 67.0011
CSV_FILE = "karachi_aqi_data.csv"

# ✅ Step 4: Fetch OpenWeather data
def fetch_openweather():
    url = f"http://api.openweathermap.org/data/2.5/weather?lat={LAT}&lon={LON}&appid={OPENWEATHER_API_KEY}&units=metric"
    r = requests.get(url).json()
    return {
        "temp": r["main"]["temp"],
        "humidity": r["main"]["humidity"],
        "pressure": r["main"]["pressure"],
        "wind_speed": r["wind"]["speed"]
    }

# ✅ Step 5: Fetch AQI data from AQICN
def fetch_aqicn():
    url = f"https://api.waqi.info/feed/geo:{LAT};{LON}/?token={AQICN_API_TOKEN}"
    r = requests.get(url).json()
    iaqi = r["data"]["iaqi"]
    return {
        "aqi": r["data"]["aqi"],
        "pm25": iaqi.get("pm25", {}).get("v"),
        "pm10": iaqi.get("pm10", {}).get("v"),
        "co": iaqi.get("co", {}).get("v"),
        "no2": iaqi.get("no2", {}).get("v"),
        "so2": iaqi.get("so2", {}).get("v"),
        "o3": iaqi.get("o3", {}).get("v")
    }

# ✅ Step 6: Combine all features
def get_data_row():
    now = datetime.utcnow()
    time_features = {
        "datetime": now,
        "hour": now.hour,
        "day": now.day,
        "month": now.month,
        "weekday": now.weekday()
    }
    return {**time_features, **fetch_openweather(), **fetch_aqicn()}

# ✅ Step 7: Save to CSV
row = get_data_row()
df_new = pd.DataFrame([row])

if os.path.exists(CSV_FILE):
    df_old = pd.read_csv(CSV_FILE)
    df = pd.concat([df_old, df_new], ignore_index=True)
else:
    df = df_new

df.to_csv(CSV_FILE, index=False)
print("✅ Data collected and saved to", CSV_FILE)

df

















