name: Daily AQI Collection

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run AQI fetch script
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        AQICN_API_TOKEN: ${{ secrets.AQICN_API_TOKEN }}
      run: python aqi_data_collection.py

    - name: Commit updated CSV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/*
        git commit -m "📥 Daily AQI update" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

